version: "3.8"

services:
  mongo:
    image: mongo:6.0.3
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db
      - './mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: mongo
      MONGO_USER: dominion
      MONGO_PASSWORD: dominion
      MONGO_DB_NAME: mongo

volumes:
  mongo:
